### ISSUE TITLE
Changing `ULdepth`

### ISSUE THREAD

**Issue by ascherer** [alexwlchan/alexwlchan.net#284]
Please use `\setlength` instead of `\renewcommand` here: https://github.com/alexwlchan/alexwlchan.net/blob/1612c06ce64fab4d4752045b587b590594f0f654/misc/latex-underlines/example_ulem_uldepth.tex#L5

See `texdoc ulem`, page 2.

**Comment by alexwlchan** [comment]
Very very belatedly, thank you for raising this! I'm going to change it shortly.
