### ISSUE TITLE
encode_email()

### ISSUE THREAD

**Issue by r0f1** [alexwlchan/alexwlchan.net#319]
Hi, I read [your tutorial on encoding email addresses](https://github.com/alexwlchan/alexwlchan.net/blob/live/src/_posts/2019/2019-06-15-a-jekyll-filter-for-obfuscating-email-addresses.md) and tried to deploy it. However I get an error in the function `encode_email()`: It seems that the string `addr` does not have an attribute called `chars`. 
Stacktrace: 
```
 Liquid Exception: undefined method `chars' for nil:NilClass in /_layouts/default.html
bundler: failed to load command: jekyll (/home/flo/gems/bin/jekyll)
NoMethodError: undefined method `chars' for nil:NilClass
  /mnt/c/Users/.../_plugins/obfuscate_email.rb:35:in `encode_email'
  /mnt/c/Users/.../_plugins/obfuscate_email.rb:45:in `create_mailto_link'
```

Could you maybe tell me how to fix this? Thanks.

**Comment by alexwlchan** [comment]
Looks like you’re passing a nil value into the `encode_email` filter.

I assume you're doing something like `{{ my_email_address | encode_email }}`, where `my_email_address` is a variable. What do you see on the page if you use `{{ my_email_address }}`?

**Comment by r0f1** [comment]
Ah thank you! Sorry, I am new to Ruby. The error was on my end. I was passing a variable that did not exist to the function. However, it is still not fully working. 
In my `footer.html` I have the following line now:

```<li>{{ site.email | create_mailto_link }}</li>```

However, when I let Jekyll render my website, this is the result:

```<li><a href="mailto:myname@example.com">myname@example.com</a></li>```

So, yes, the function you have posted works, but in the source code of my website, the email address is still clearly visible and its characters are not substituted by `&#x123`. Do you happen to know why this could be? Does Jenkyll undo the subsitution? I know this is "out of the scope", but I am just curious. If you don't know the answer just feel free to close this issue :)

**Comment by alexwlchan** [comment]
Hmm. I can’t think why Jekyll would be undoing it.

Where are you checking the rendered HTML? The developer tools in some browsers will undo the encoding for you; you have to inspect the raw source to see the HTML entities.

**Comment by r0f1** [comment]
Thanks!! Yes, Chrome was undoing it. Thank you very much.

**Comment by alexwlchan** [comment]
Glad you got it working! 🎉
